<?xml version="1.0" encoding="utf-8"?><Database Name="Laboratorio" Class="ConnectionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=GMEPN001045\SQLEXPRESS;Initial Catalog=Laboratorio;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LaboratorioConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PESSOA" Member="PESSOA">
    <Type Name="PESSOA">
      <Column Name="CPF" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NOME" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENERO" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SENHA" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>