#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaDeTarefas.connection
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Laboratorio")]
	public partial class connectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPESSOA(PESSOA instance);
    partial void UpdatePESSOA(PESSOA instance);
    partial void DeletePESSOA(PESSOA instance);
    partial void InsertTAREFA(TAREFA instance);
    partial void UpdateTAREFA(TAREFA instance);
    partial void DeleteTAREFA(TAREFA instance);
    #endregion
		
		public connectionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LaboratorioConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public connectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public connectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public connectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public connectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PESSOA> PESSOA
		{
			get
			{
				return this.GetTable<PESSOA>();
			}
		}
		
		public System.Data.Linq.Table<TAREFA> TAREFA
		{
			get
			{
				return this.GetTable<TAREFA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PESSOA")]
	public partial class PESSOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CPF;
		
		private string _NOME;
		
		private string _EMAIL;
		
		private string _GENERO;
		
		private string _SENHA;
		
		private int _ID;
		
		private EntitySet<TAREFA> _TAREFA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCPFChanging(long value);
    partial void OnCPFChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnGENEROChanging(string value);
    partial void OnGENEROChanged();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public PESSOA()
		{
			this._TAREFA = new EntitySet<TAREFA>(new Action<TAREFA>(this.attach_TAREFA), new Action<TAREFA>(this.detach_TAREFA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="BigInt NOT NULL")]
		public long CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENERO", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string GENERO
		{
			get
			{
				return this._GENERO;
			}
			set
			{
				if ((this._GENERO != value))
				{
					this.OnGENEROChanging(value);
					this.SendPropertyChanging();
					this._GENERO = value;
					this.SendPropertyChanged("GENERO");
					this.OnGENEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PESSOA_TAREFA", Storage="_TAREFA", ThisKey="ID", OtherKey="RESPONSAVEL_ID")]
		public EntitySet<TAREFA> TAREFA
		{
			get
			{
				return this._TAREFA;
			}
			set
			{
				this._TAREFA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAREFA(TAREFA entity)
		{
			this.SendPropertyChanging();
			entity.PESSOA = this;
		}
		
		private void detach_TAREFA(TAREFA entity)
		{
			this.SendPropertyChanging();
			entity.PESSOA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAREFA")]
	public partial class TAREFA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TITULO;
		
		private string _DESCRICAO;
		
		private System.DateTime _DT_INICIO;
		
		private System.Nullable<System.DateTime> _DT_FIM;
		
		private int _RESPONSAVEL_ID;
		
		private EntityRef<PESSOA> _PESSOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTITULOChanging(string value);
    partial void OnTITULOChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnDT_INICIOChanging(System.DateTime value);
    partial void OnDT_INICIOChanged();
    partial void OnDT_FIMChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_FIMChanged();
    partial void OnRESPONSAVEL_IDChanging(int value);
    partial void OnRESPONSAVEL_IDChanged();
    #endregion
		
		public TAREFA()
		{
			this._PESSOA = default(EntityRef<PESSOA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this.OnTITULOChanging(value);
					this.SendPropertyChanging();
					this._TITULO = value;
					this.SendPropertyChanged("TITULO");
					this.OnTITULOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_INICIO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_INICIO
		{
			get
			{
				return this._DT_INICIO;
			}
			set
			{
				if ((this._DT_INICIO != value))
				{
					this.OnDT_INICIOChanging(value);
					this.SendPropertyChanging();
					this._DT_INICIO = value;
					this.SendPropertyChanged("DT_INICIO");
					this.OnDT_INICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_FIM", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_FIM
		{
			get
			{
				return this._DT_FIM;
			}
			set
			{
				if ((this._DT_FIM != value))
				{
					this.OnDT_FIMChanging(value);
					this.SendPropertyChanging();
					this._DT_FIM = value;
					this.SendPropertyChanged("DT_FIM");
					this.OnDT_FIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESPONSAVEL_ID", DbType="Int NOT NULL")]
		public int RESPONSAVEL_ID
		{
			get
			{
				return this._RESPONSAVEL_ID;
			}
			set
			{
				if ((this._RESPONSAVEL_ID != value))
				{
					if (this._PESSOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRESPONSAVEL_IDChanging(value);
					this.SendPropertyChanging();
					this._RESPONSAVEL_ID = value;
					this.SendPropertyChanged("RESPONSAVEL_ID");
					this.OnRESPONSAVEL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PESSOA_TAREFA", Storage="_PESSOA", ThisKey="RESPONSAVEL_ID", OtherKey="ID", IsForeignKey=true)]
		public PESSOA PESSOA
		{
			get
			{
				return this._PESSOA.Entity;
			}
			set
			{
				PESSOA previousValue = this._PESSOA.Entity;
				if (((previousValue != value) 
							|| (this._PESSOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PESSOA.Entity = null;
						previousValue.TAREFA.Remove(this);
					}
					this._PESSOA.Entity = value;
					if ((value != null))
					{
						value.TAREFA.Add(this);
						this._RESPONSAVEL_ID = value.ID;
					}
					else
					{
						this._RESPONSAVEL_ID = default(int);
					}
					this.SendPropertyChanged("PESSOA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
