USE [Laboratorio]
GO

/****** Object:  Table [dbo].[DIARIO]    Script Date: 06/11/2019 16:34:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITULO] [nvarchar](50) NOT NULL,
	[NOME] [nvarchar](50) NOT NULL,
	[DATA_CRIACAO] [datetime] NOT NULL,
	[DESCRICAO] [nvarchar](max) NOT NULL,
	[ARQUIVO] [varbinary](max) NULL,
 CONSTRAINT [PK_DIARIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


