#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="labRodrigues")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCOLABORADOR(COLABORADOR instance);
    partial void UpdateCOLABORADOR(COLABORADOR instance);
    partial void DeleteCOLABORADOR(COLABORADOR instance);
    partial void InsertFILHO(FILHO instance);
    partial void UpdateFILHO(FILHO instance);
    partial void DeleteFILHO(FILHO instance);
    partial void InsertFUNCIONARIOS(FUNCIONARIOS instance);
    partial void UpdateFUNCIONARIOS(FUNCIONARIOS instance);
    partial void DeleteFUNCIONARIOS(FUNCIONARIOS instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::Model.Properties.Settings.Default.labRodriguesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<COLABORADOR> COLABORADOR
		{
			get
			{
				return this.GetTable<COLABORADOR>();
			}
		}
		
		public System.Data.Linq.Table<FILHO> FILHO
		{
			get
			{
				return this.GetTable<FILHO>();
			}
		}
		
		public System.Data.Linq.Table<FUNCIONARIOS> FUNCIONARIOS
		{
			get
			{
				return this.GetTable<FUNCIONARIOS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COLABORADOR")]
	public partial class COLABORADOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOME;
		
		private int _MATRICULA;
		
		private string _TELEFONE;
		
		private string _CONJUGE;
		
		private string _EMAIL;
		
		private int _ID;
		
		private EntitySet<FILHO> _FILHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnMATRICULAChanging(int value);
    partial void OnMATRICULAChanged();
    partial void OnTELEFONEChanging(string value);
    partial void OnTELEFONEChanged();
    partial void OnCONJUGEChanging(string value);
    partial void OnCONJUGEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public COLABORADOR()
		{
			this._FILHO = new EntitySet<FILHO>(new Action<FILHO>(this.attach_FILHO), new Action<FILHO>(this.detach_FILHO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATRICULA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATRICULA
		{
			get
			{
				return this._MATRICULA;
			}
			set
			{
				if ((this._MATRICULA != value))
				{
					this.OnMATRICULAChanging(value);
					this.SendPropertyChanging();
					this._MATRICULA = value;
					this.SendPropertyChanged("MATRICULA");
					this.OnMATRICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONE", DbType="NVarChar(50)")]
		public string TELEFONE
		{
			get
			{
				return this._TELEFONE;
			}
			set
			{
				if ((this._TELEFONE != value))
				{
					this.OnTELEFONEChanging(value);
					this.SendPropertyChanging();
					this._TELEFONE = value;
					this.SendPropertyChanged("TELEFONE");
					this.OnTELEFONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONJUGE", DbType="NVarChar(50)")]
		public string CONJUGE
		{
			get
			{
				return this._CONJUGE;
			}
			set
			{
				if ((this._CONJUGE != value))
				{
					this.OnCONJUGEChanging(value);
					this.SendPropertyChanging();
					this._CONJUGE = value;
					this.SendPropertyChanged("CONJUGE");
					this.OnCONJUGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COLABORADOR_FILHO", Storage="_FILHO", ThisKey="MATRICULA", OtherKey="PAI")]
		public EntitySet<FILHO> FILHO
		{
			get
			{
				return this._FILHO;
			}
			set
			{
				this._FILHO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_FILHO(FILHO entity)
		{
			this.SendPropertyChanging();
			entity.COLABORADOR = this;
		}
		
		private void detach_FILHO(FILHO entity)
		{
			this.SendPropertyChanging();
			entity.COLABORADOR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FILHO")]
	public partial class FILHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOME;
		
		private string _FAIXA_ETARIA;
		
		private int _ID;
		
		private int _PAI;
		
		private EntityRef<COLABORADOR> _COLABORADOR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnFAIXA_ETARIAChanging(string value);
    partial void OnFAIXA_ETARIAChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPAIChanging(int value);
    partial void OnPAIChanged();
    #endregion
		
		public FILHO()
		{
			this._COLABORADOR = default(EntityRef<COLABORADOR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAIXA_ETARIA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FAIXA_ETARIA
		{
			get
			{
				return this._FAIXA_ETARIA;
			}
			set
			{
				if ((this._FAIXA_ETARIA != value))
				{
					this.OnFAIXA_ETARIAChanging(value);
					this.SendPropertyChanging();
					this._FAIXA_ETARIA = value;
					this.SendPropertyChanged("FAIXA_ETARIA");
					this.OnFAIXA_ETARIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAI", DbType="Int NOT NULL")]
		public int PAI
		{
			get
			{
				return this._PAI;
			}
			set
			{
				if ((this._PAI != value))
				{
					if (this._COLABORADOR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPAIChanging(value);
					this.SendPropertyChanging();
					this._PAI = value;
					this.SendPropertyChanged("PAI");
					this.OnPAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COLABORADOR_FILHO", Storage="_COLABORADOR", ThisKey="PAI", OtherKey="MATRICULA", IsForeignKey=true)]
		public COLABORADOR COLABORADOR
		{
			get
			{
				return this._COLABORADOR.Entity;
			}
			set
			{
				COLABORADOR previousValue = this._COLABORADOR.Entity;
				if (((previousValue != value) 
							|| (this._COLABORADOR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COLABORADOR.Entity = null;
						previousValue.FILHO.Remove(this);
					}
					this._COLABORADOR.Entity = value;
					if ((value != null))
					{
						value.FILHO.Add(this);
						this._PAI = value.MATRICULA;
					}
					else
					{
						this._PAI = default(int);
					}
					this.SendPropertyChanged("COLABORADOR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FUNCIONARIOS")]
	public partial class FUNCIONARIOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NOME;
		
		private int _MATRICULA;
		
		private string _TELEFONE;
		
		private string _EMAIL;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnMATRICULAChanging(int value);
    partial void OnMATRICULAChanged();
    partial void OnTELEFONEChanging(string value);
    partial void OnTELEFONEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public FUNCIONARIOS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATRICULA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATRICULA
		{
			get
			{
				return this._MATRICULA;
			}
			set
			{
				if ((this._MATRICULA != value))
				{
					this.OnMATRICULAChanging(value);
					this.SendPropertyChanging();
					this._MATRICULA = value;
					this.SendPropertyChanged("MATRICULA");
					this.OnMATRICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONE", DbType="NVarChar(50)")]
		public string TELEFONE
		{
			get
			{
				return this._TELEFONE;
			}
			set
			{
				if ((this._TELEFONE != value))
				{
					this.OnTELEFONEChanging(value);
					this.SendPropertyChanging();
					this._TELEFONE = value;
					this.SendPropertyChanged("TELEFONE");
					this.OnTELEFONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
