#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluxoDeProcessos.Connection
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Laboratorio")]
	public partial class ConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPROCESSO(PROCESSO instance);
    partial void UpdatePROCESSO(PROCESSO instance);
    partial void DeletePROCESSO(PROCESSO instance);
    #endregion
		
		public ConnectionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LaboratorioConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PROCESSO> PROCESSO
		{
			get
			{
				return this.GetTable<PROCESSO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROCESSO")]
	public partial class PROCESSO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NUMERO_PROCESSO;
		
		private decimal _VALOR;
		
		private string _ESCRITORIO;
		
		private System.DateTime _DATA_CRIACAO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNUMERO_PROCESSOChanging(string value);
    partial void OnNUMERO_PROCESSOChanged();
    partial void OnVALORChanging(decimal value);
    partial void OnVALORChanged();
    partial void OnESCRITORIOChanging(string value);
    partial void OnESCRITORIOChanged();
    partial void OnDATA_CRIACAOChanging(System.DateTime value);
    partial void OnDATA_CRIACAOChanged();
    #endregion
		
		public PROCESSO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_PROCESSO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NUMERO_PROCESSO
		{
			get
			{
				return this._NUMERO_PROCESSO;
			}
			set
			{
				if ((this._NUMERO_PROCESSO != value))
				{
					this.OnNUMERO_PROCESSOChanging(value);
					this.SendPropertyChanging();
					this._NUMERO_PROCESSO = value;
					this.SendPropertyChanged("NUMERO_PROCESSO");
					this.OnNUMERO_PROCESSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="Decimal(18,0) NOT NULL")]
		public decimal VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this.OnVALORChanging(value);
					this.SendPropertyChanging();
					this._VALOR = value;
					this.SendPropertyChanged("VALOR");
					this.OnVALORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESCRITORIO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ESCRITORIO
		{
			get
			{
				return this._ESCRITORIO;
			}
			set
			{
				if ((this._ESCRITORIO != value))
				{
					this.OnESCRITORIOChanging(value);
					this.SendPropertyChanging();
					this._ESCRITORIO = value;
					this.SendPropertyChanged("ESCRITORIO");
					this.OnESCRITORIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_CRIACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DATA_CRIACAO
		{
			get
			{
				return this._DATA_CRIACAO;
			}
			set
			{
				if ((this._DATA_CRIACAO != value))
				{
					this.OnDATA_CRIACAOChanging(value);
					this.SendPropertyChanging();
					this._DATA_CRIACAO = value;
					this.SendPropertyChanged("DATA_CRIACAO");
					this.OnDATA_CRIACAOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
