USE [Laboratorio]
GO

/****** Object:  Table [dbo].[TAREFA]    Script Date: 14/10/2019 15:59:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TAREFA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITULO] [nvarchar](50) NOT NULL,
	[DESCRICAO] [nvarchar](max) NOT NULL,
	[DT_INICIO] [datetime] NOT NULL,
	[DT_FIM] [datetime] NULL,
	[RESPONSAVEL_ID] [int] NOT NULL,
 CONSTRAINT [PK_TAREFA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TAREFA]  WITH CHECK ADD  CONSTRAINT [FK_TAREFA_RESPONSAVEL] FOREIGN KEY([RESPONSAVEL_ID])
REFERENCES [dbo].[PESSOA] ([ID])
GO

ALTER TABLE [dbo].[TAREFA] CHECK CONSTRAINT [FK_TAREFA_RESPONSAVEL]
GO

