USE [master]
GO

/****** Object:  Database [Laboratorio]    Script Date: 09/10/2019 17:22:30 ******/
CREATE DATABASE [Laboratorio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Laboratorio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Laboratorio.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Laboratorio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Laboratorio_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Laboratorio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Laboratorio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Laboratorio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Laboratorio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Laboratorio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Laboratorio] SET ARITHABORT OFF 
GO

ALTER DATABASE [Laboratorio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Laboratorio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Laboratorio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Laboratorio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Laboratorio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Laboratorio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Laboratorio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Laboratorio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Laboratorio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Laboratorio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Laboratorio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Laboratorio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Laboratorio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Laboratorio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Laboratorio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Laboratorio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Laboratorio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Laboratorio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Laboratorio] SET  MULTI_USER 
GO

ALTER DATABASE [Laboratorio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Laboratorio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Laboratorio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Laboratorio] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Laboratorio] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Laboratorio] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Laboratorio] SET  READ_WRITE 
GO

