USE [labRodrigues]
GO

/****** Object:  Table [dbo].[COLABORADOR]    Script Date: 07/10/2019 15:41:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COLABORADOR](
	[NOME] [nvarchar](50) NOT NULL,
	[MATRICULA] [int] NOT NULL,
	[TELEFONE] [nvarchar](50) NULL,
	[CONJUGE] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_COLABORADOR] PRIMARY KEY CLUSTERED 
(
	[MATRICULA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

