USE [labRodrigues]
GO

/****** Object:  Table [dbo].[FILHO]    Script Date: 07/10/2019 15:41:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FILHO](
	[NOME] [nvarchar](50) NOT NULL,
	[FAIXA_ETARIA] [nvarchar](50) NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAI] [int] NOT NULL,
 CONSTRAINT [PK_FILHO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FILHO]  WITH CHECK ADD  CONSTRAINT [FK_FILHO_PAI] FOREIGN KEY([PAI])
REFERENCES [dbo].[COLABORADOR] ([MATRICULA])
GO

ALTER TABLE [dbo].[FILHO] CHECK CONSTRAINT [FK_FILHO_PAI]
GO

