USE [Laboratorio]
GO

/****** Object:  Table [dbo].[PROCESSO]    Script Date: 16/10/2019 16:48:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROCESSO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NUMERO_PROCESSO] [nvarchar](50) NOT NULL,
	[VALOR] [decimal](18, 2) NOT NULL,
	[ESCRITORIO] [nvarchar](50) NOT NULL,
	[DATA_CRIACAO] [datetime] NOT NULL,
 CONSTRAINT [PK_PROCESSO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

